//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emdep.Geos.Data.Common.OTMDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailattachment
    {
        public long IdAttachment { get; set; }
        public long IdEmail { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public System.DateTime CreatedIn { get; set; }
        public Nullable<System.DateTime> ModifiedIn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string AttachmentExtension { get; set; }
        public byte[] FileContent { get; set; }
        public virtual email email { get; set; }

    }
}
