using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace Emdep.Geos.Modules.PCM.Views
{
    /// <summary>
    /// Interaction logic for ProductTypeArticleView.xaml
    /// </summary>
    public partial class ProductTypeArticleView : UserControl
    {
        public ProductTypeArticleView()
        {
            InitializeComponent();
        }

        private void GridCategoryMenuList_AutoGeneratedColumns(object sender, RoutedEventArgs e)
        {

        }

        private void ArticleCategoryMenutreeListView_CompleteRecordDragDrop(object sender, DevExpress.Xpf.Core.CompleteRecordDragDropEventArgs e)
        {
            e.Handled = false;
        }
    }
}
