//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public long IdEmail { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string RecipientName { get; set; }
        public string RecipientEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> CreatedIn { get; set; }
        public Nullable<System.DateTime> ModifiedIn { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }

        public List<emailattachment> Attachments { get; set; }
    }
}
